server:
  port: 9527
logging:
  config: classpath:log4j2-spring.xml
spring:
  application:
    name: gateway9527
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    gateway:
      routes:
        - id: payment_route # 路由的ID，没有固定的规则，但要求唯一，建议配合服务名
          uri: http://localhost:8001 # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，根据路径匹配进行路由
#            - Path=/payment/**

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须配置true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka
  instance:
    # 修改Eureka中Status服务名
    instance-id: gateway9527
    # 访问路径可以显示ip地址
    prefer-ip-address: true