server:
  port: 92
logging:
  config: classpath:log4j2-spring.xml
spring:
  application:
    name: consumer-order92
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719 # 默认8719
      # 将sentinel配置持久化到nacos中保存
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

service-url:
  payment-service: http://payment-service/payment

# 激活feign对sentinel的支持，默认为false
feign:
  sentinel:
    enabled: true